sudo: required
language: generic
services:
        - docker


before_install:
        - docker build -t react-test -f ./client/Dockerfile.dev ./client

scripts:
        - docker run -e CI=true react-test npm test


after_success:
        - docker build -t tobeortoc/multi-client ./client
        - docker build -t tobeortoc/multi-nginx ./nginx
        - docker build -t tobeortoc/multi-server ./server
        - docker build -t tobeortoc/multi-worker ./worker

#Login to Docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
        - docker push tobeortoc/multi-client
        - docker push tobeortoc/multi-nginx
        - docker push tobeortoc/multi-server
        - docker push tobeortoc/multi-worker
       

## Push images to Docker hub
